### ISSUE TITLE
项目目录为什么这么奇怪，gmsec目录里面的东西为什么不放在根目录里面

### ISSUE THREAD

**Issue by evildao** [gmsec/gmsec#3]

**Comment by xxjwxc** [comment]
主要是有一个paidoc，文件夹主要定义不同微服务的proto文件。

**Comment by xxjwxc** [comment]
多个微服务并列，gmsec定义的是其中一个微服务。后边多服务，更目录再定义。

**Comment by evildao** [comment]
原来如此，不过如此一来的话，gmsec目录下的proto套件目前就没必要弄进去了，有点误导不说，里面 `ln -s ../rpc ./` 对win环境的人也不是很友好

**Comment by xxjwxc** [comment]
是的，porto可以删掉。

软连接(ln)方案主要因为go mod问题。只能包含到本项目目录。所以建立的ln。如果有更好的方案也可以参考。

**Comment by evildao** [comment]
调整完了，我测试了一下，貌似没啥问题

**Comment by xxjwxc** [comment]
用replace 代替 ln ？

**Comment by xxjwxc** [comment]
windows 更新了一些文件布局方案。
