### ISSUE TITLE
安装遇到问题

### ISSUE THREAD

**Issue by CasonTsai** [gmsec/gmsec#9]
大佬，，请问在windows安装遇到这些依赖库问题
..\src\github.com\go-playground\validator\errors.go:9:2: cannot find package "github.com/go-playground/universal-translator" in any of:
	E:\CodeTool\Golang\install\src\github.com\go-playground\universal-translator (from $GOROOT)
	E:\Learn\Go\src\github.com\go-playground\universal-translator (from $GOPATH)
..\src\github.com\go-playground\validator\baked_in.go:23:2: cannot find package "github.com/leodido/go-urn" in any of:
	E:\CodeTool\Golang\install\src\github.com\leodido\go-urn (from $GOROOT)
	E:\Learn\Go\src\github.com\leodido\go-urn (from $GOPATH)
..\src\github.com\gmsec\micro\registry\dns_naming_register.go:16:2: cannot find package "github.com/micro/mdns" in any of:
	E:\CodeTool\Golang\install\src\github.com\micro\mdns (from $GOROOT)
	E:\Learn\Go\src\github.com\micro\mdns (from $GOPATH)
..\src\github.com\gmsec\goplugins\plugin\gin.go:14:2: cannot find package "github.com/soheilhy/cmux" in any of:
	E:\CodeTool\Golang\install\src\github.com\soheilhy\cmux (from $GOROOT)
	E:\Learn\Go\src\github.com\soheilhy\cmux (from $GOPATH)
remote_project\ShengHuaYiXue\main.go:15:2: cannot find package "gmsec/rpc/gmsec" in any of:
	E:\CodeTool\Golang\install\src\gmsec\rpc\gmsec (from $GOROOT)
	E:\Learn\Go\src\gmsec\rpc\gmsec (from $GOPATH)
..\src\github.com\go-playground\validator\baked_in.go:20:2: cannot find package "golang.org/x/crypto/sha3" in any of:
	E:\CodeTool\Golang\install\src\golang.org\x\crypto\sha3 (from $GOROOT)
	E:\Learn\Go\src\golang.org\x\crypto\sha3 (from $GOPATH)

有些依赖库显示的路径无效是怎么回事

**Comment by xxjwxc** [comment]
go mod 的问题？
